# results_folder: /scratch/tweber/DATA/1000G_SNV_with_GT/OTF
# results_folder: /scratch/tsapalou_template/DATA/GENOTYPING/1000G_SNV_with_GT/RESULTS
# results_folder: /scratch/tweber/DATA/1000G_SNV_with_GT/RESULTS
# onekgp_vcf_folder: /scratch/tweber/DATA/1000G_SNV_with_GT/VCF
# onekgp_vcf_folder: /scratch/tsapalou_template/DATA/GENOTYPING/1000G_SNV_with_GT/VCF
# bam_folder: /g/korbel2/weber/MosaiCatcher_files/POOLING/POOL1_RESEQ
# bam_folder: /scratch/tweber/DATA/MC_DATA/HGSVC/POOLS_BAM
bam_folder: /scratch/tweber/DATA/MC_DATA/STOCKS/2023-11-09-HW3YVAFX5
onekgp_vcf_folder: /scratch/tweber/DATA/MC_DATA/DEMULTIPLEXING_POOLS/1000G_SNV_with_GT/HGSVC2_1KG_3202_VCF_FILES_RENAMED_SYMLINK
# onekgp_vcf_folder: /g/korbel/weber/MosaiCatcher_files/EXTERNAL_DATA/snv_sites_to_genotype/1000G_SNV_with_GT/HGSVC2_1KG_3202_VCF_FILES_RENAMED_SYMLINK
results_folder: /scratch/tweber/DATA/MC_DATA/DEMULTIPLEXING_POOLS
tmp_data_folder: /tmpdata/tweber/bcftools/
fasta_ref: /g/korbel2/weber/MosaiCatcher_files/EXTERNAL_DATA/refgenomes_human_local/hg38.complete.fa
samples_pooled:
  LanexHGSVCpool2NEW:
    - HG00238
    - HG00342
    - HG00479
    - HG00623
    - HG00702
    - HG00705
    - HG00739
    - HG01800
    - HG02014
    - HG02155
    - HG02178
    - HG02190
    - HG02312
    - HG02485
    - HG02643
    - HG02679
    - HG02793
    - HG02944
    - HG03121
    - HG03133
    - HG03369
    - HG03371
    - HG03548
    - HG03673
    - HG03812
    - HG03882
    - HG03897
    - NA10861
    # - NA18540
    - NA18566
    - NA18879
    - NA18907
    - NA18913
    - NA18941
    - NA19451
    - NA19455
    - NA19788
    - NA20525
    - NA20861
    - NA21126
